sudo: required

language: python

python:
  - "3.5"

# Travis stuck on old version of MongoDB 2.4.12
#services:
#  - mongodb

env:
  MONGODB_URI: 127.0.0.1
  MONGODB_DB_NAME: test

before_install:
  - pip install coveralls

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get -y update
  - sudo apt-get install -y mongodb-org=3.2.11 mongodb-org-server=3.2.11 mongodb-org-shell=3.2.11 mongodb-org-mongos=3.2.11 mongodb-org-tools=3.2.11
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version

script:
  - py.test --cov todo --cov-report term-missing

after_success:
  - coveralls
